### PR TITLE
Added Czech translation.

### PR DESCRIPTION
**Pull request by Blokatt**

### CODE REVIEW

**Comment by hamukazu** [comment]
Czech translation is also requested in #109. I cannot judge which is better. Please discuss between the contributors. Thanks.

**Comment by coosa** [comment]
In my opinion, the one from Blokatt looks better. It also has a link to Czech media covering the case.

**Comment by Blokatt** [comment]
With all due respect to coosa, I believe my version sounds a lot more natural (theirs is more of a direct translation without additional paraphrasing/reinterpretation).
As far as I can tell, it's also typo-free.

**Comment by hamukazu** [comment]
I still do not understand it, but I believe you and merge it. Thanks.

**Pull request merged**
