### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by lvm**
Similar to other languages, a translation for Spanish language (in es_AR)

### CODE REVIEW

**Comment by hamukazu** [comment]
Since I have too many translation requests,  I am going to divide README.md into multiple files. Wait for a moment. Thanks.

**Comment by hamukazu** [comment]
This is merged in b8c5de3 as a new file. Thanks a lot!

**Comment by hamukazu** [comment]
Sorry there was a mistake in the commit. This is fixed in 4663c4.

**Comment by lvm** [comment]
Excellent! Thanks!

**Pull request closed without merging**
