### PR TITLE
Introduce zh-hant as traditional chinese and update zh-hans as simplified chinese

### PR DESCRIPTION
**Pull request by orbli**

### CODE REVIEW

**Comment by el-hoshino** [comment]
I don't want to bring necessary political argument into this project, but I don't see the meaning of "gb" and "zh" pair.

"gb", a short term of "GB2312" is a text encoding system just like UTF-8, or SHIFT-JIS for Japanese, while "zh" stands for "中文", a short term of a language. They're not a pair.

I personally do understand that you Hong Kong guys consider the "Simplified Chinese" is not a correct form, but the "Traditional Chinese" is. I don't want to argue about this since it has nothing to do with this project. What I suggest is, change the simplified chinese file name into `zh_CN` or `zh_Hans`, and add the traditional chinese file with name `zh_HK` or `zh_Hant`. Everybody would be happy.

**Comment by orbli** [comment]
sorry for my insufficient knowledge to the notations on iso, I'm ok with your proposal.

**Comment by orbli** [comment]
now it is ready to be merged

**Comment by el-hoshino** [comment]
Very appreciated 😃

**Pull request merged**
