### PR TITLE
Add Chinese translation to README.md

### PR DESCRIPTION
**Pull request by el-hoshino**

### CODE REVIEW

**Comment by 1amageek** [comment]
Great job👍

**Comment by shuye02** [comment]
Good job, appreciate it!

**Comment by hamukazu** [comment]
Because I have too many translation requests,  I am going to divide README.md into multiple files. Wait for a moment. Thanks.

**Comment by hamukazu** [comment]
This is merged as a new file in 4615505. Thanks a lot!

**Pull request closed without merging**
